### ISSUE TITLE
rust produces a 2.1G executable

### ISSUE THREAD

**Issue by laanwj** [rust-embedded/riscv-rt#24]
I'm trying to build a project for the HiFive board with the current rust nightly, commit ef8c16350fc8b554c500c361f7a0eb574fef1a31 of `riscv-rt`, and `riscv32imac-unknown-none-elf` toolchain, but I'm running into a strange issue.

The resulting executable is:
```
-rwxrwxr-x 2 user user 2.1G Feb 28 15:51 ./target/riscv32imac-unknown-none-elf/release/examples/blinky_delay
```

`readelf -a` shows that it's the `.stack` section that takes up all this space:
```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        20400000 001000 000252 00  AX  0   0 16
  [ 2] .bss              NOBITS          80000000 002000 000004 00  WA  0   0  1
  [ 3] .data             PROGBITS        80000004 001252 000000 00  WA  0   0  1
  [ 4] .heap             PROGBITS        80000004 001254 000000 00   W  0   0  4
  [ 5] .stack            PROGBITS        80000004 001254 80004000 00   W  0   0  4
  [ 6] .debug_str        PROGBITS        00000000 80005254 00500a 01  MS  0   0  1
```
I'm using the `link.x` from this crate, and `memory.x` from `e310x-hal` (https://github.com/riscv-rust/e310x-hal/blob/master/memory.x) which indeed places RAM at offset `0x80000000`.

This is the first time I'm working with rust on bare-metal. I suspect this is a problem with the linker script accidentally telling to provide data bits for the bss segments?

**Comment by Disasm** [comment]
Thanks for the report!
How do you build your example?

**Comment by laanwj** [comment]
```
cargo +nightly build --release --example blinky_delay
```
the cargo config is:
```
[target.riscv32imac-unknown-none-elf]
runner = 'riscv32-unknown-elf-gdb'
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-melf32lriscv",
  "-C", "linker=riscv64-linux-gnu-ld",
]

[build]
target = "riscv32imac-unknown-none-elf"
```
(I'm buliding in a `riscv-crates` in which I updated the component modules, nothing else works for me, I was happy to have an executable at all; if there's a recent example that simply works that'd be awesome!)

**Comment by Disasm** [comment]
> `riscv64-linux-gnu-ld`

This is the problem. In fact, you do not need this. As alternative, you can install official toolchain and use it to build an example.

**Comment by Disasm** [comment]
I will try to update these examples soon, so stay tuned!

**Comment by laanwj** [comment]
Thank you very much, removing those lines solved the problem!
```
-rwxrwxr-x 2 user user 72K Feb 28 16:18 ./target/riscv32imac-unknown-none-elf/release/examples/blinky_delay
```

**Comment by laanwj** [comment]
> I will try to update these examples soon, so stay tuned!

Would be great—FWIW the main problems I ran into is that `hifive` and possibly some others depend on another specific version of `riscv-rt` (0.3.0 versus 0.4.0), causing build issues with current nightly (`feature(panic_implementation)` has been removed) as well as linking multiple versions of this crate to be linked resulting in duplicate  `_start_rust` error.

**Comment by Disasm** [comment]
@laanwj Update submodules once again. They should be consistent now.
