### ISSUE TITLE
LiteX/VexRiscv support

### ISSUE THREAD

**Issue by vshymanskyy** [rust-embedded/riscv-rt#39]
Will this work on VexRiscv?
If not, what changes may be needed to enable support for this? Thanks!

**Comment by Disasm** [comment]
The answer is: it depends. If your instance of VexRiscv has M extension and supports Privileged ISA Specification, then yes, this will work.
Cores without M extension can be supported with some changes, but for cores without Privileged ISA Specification this crate is useless.

**Comment by tomtor** [comment]
See https://github.com/tomtor/rust-litex

**Comment by Disasm** [comment]
Closing, as riscv32i support is now released in v0.7

**Comment by vshymanskyy** [comment]
Thanks!
