### ISSUE TITLE
Execution start address varies.

### ISSUE THREAD

**Issue by elfmimi** [rust-embedded/riscv-rt#44]
In some implementations, execution starting address may vary from what specified in the linker script, depending on conditions.

With GD32VF103, if an application is booted by DFU bootloader, PC is set to 0x0800_0000.
But when an application is booted directly, default value of PC after reset is 0x0000_0000.
- note: DFU bootloader is hard-coded in ROM and it can't be modified.

I suppose care should be taken at the beginning of start-up code. Otherwise the application will not boot properly after reset. Mainly because SP will get initialized with wrong value.

It would be something like this.

```Unix-Assembly
_start:
/* Some implementations may start execution at address 0 . */
.if __riscv_xlen == 32
    lui ra, %hi(_abs_start)
    jr %lo(_abs_start)(ra)
.endif

.if __riscv_xlen == 64
    auipc ra, %pcrel_hi(.L0)
    ld ra, %lo(.L0)(ra)
    jr ra
    .align 3, 0
.L0:
    .dword _abs_start
.endif

_abs_start:
```

I'm not sure whether this is appropriate for riscv64 platforms.

**Comment by Disasm** [comment]
There is a hack for this in gd32vf103xx-hal:
https://github.com/riscv-rust/gd32vf103xx-hal/blob/master/rebase-hack.S

**Comment by elfmimi** [comment]
@Disasm Thank you for pointing me to the right direction.
Switched from gd32vf103-hal to gd32vf103xx-hal and it worked.

But, eek! It's quite tricky!

**Comment by Disasm** [comment]
Do you mind opening a PR with your change? It seems like a good default. If I recall correctly, K210 (64-bit) chip has the same problem.
