### ISSUE TITLE
RAM init code violates pointer provenance and aliasing rules

### ISSUE THREAD

**Issue by jonas-schievink** [rust-embedded/riscv-rt#69]
RAM initialization currently passes pointers to these `static`s:

https://github.com/rust-embedded/riscv-rt/blob/47ece5f5163a2e38ce5e4685b5d3145713d7954a/src/lib.rs#L346-L355

...to `r0`:

https://github.com/rust-embedded/riscv-rt/blob/47ece5f5163a2e38ce5e4685b5d3145713d7954a/src/lib.rs#L381-L382

But since r0 will fill the entire memory range between the pointers, it ends up calling `offset` with values that create pointers well beyond the `u32` the static is declared to contain. According to the [docs of `offset`](https://doc.rust-lang.org/std/primitive.pointer.html#method.offset), this is UB:

> Both the starting and resulting pointer must be either in bounds or one byte past the end of the same allocated object. Note that in Rust, every (stack-allocated) variable is considered a separate allocated object.

(every `static` also counts as its own "allocated object", I believe)

Moreover, the `ptr::write` and `ptr::write_volatile` calls in r0 *also* cause UB, because this invariant is violated:

> dst must be valid for writes.

Where the [*validity*](https://doc.rust-lang.org/std/ptr/index.html#safety) of a pointer requires this:

> For a pointer to be valid, it is necessary, but not always sufficient, that the pointer be dereferenceable: the memory range of the given size starting at the pointer must all be within the bounds of a single allocated object. Note that in Rust, every (stack-allocated) variable is considered a separate allocated object.

...but again, we are crossing between potentially many allocated objects (every `static` in the `.data`/`.bss` section).

Furthermore, writing to a static through a pointer not derived from that static might violate aliasing rules, but it isn't yet clear if this is the case today (I've asked the folks working on the unsafe code guidelines for clarification / guidance).

The most robust solution for this issue is to write the RAM init code in assembly instead of Rust, and run no Rust code at all until RAM is initialized.

(this issue was recently discovered to affect most -rt crates in the ecosystem; we do not believe it to cause practical issues at the moment)

**Comment by romancardenas** [comment]
This should be fixed with #123. Unless someone raises any additional concerns, I'll close this issue as soon as #123 gets merged
