### ISSUE TITLE
New crates.io release

### ISSUE THREAD

**Issue by parkero** [rust-embedded/riscv-rt#85]
Would there be there any downsides to a new crates.io release with the latest changes on master?

**Comment by almindor** [comment]
Of course not. Is the CHANGELOG updated with unreleased stuff properly?

**Comment by parkero** [comment]
I do not believe so, submitted a pull request with the functionality changes I can see in the commits

**Comment by parkero** [comment]
Wanted to drop a quick thank you for the help on this @almindor, much appreciated

**Comment by almindor** [comment]
Np, don't forget @Disasm he's the real MVP :)
