### ISSUE TITLE
Accessing parameters passed in register by the previous boot stage

### ISSUE THREAD

**Issue by SimonSapin** [rust-embedded/riscv-rt#92]
When running freestanding RISC-V code in QEMU, a "Flattened Device Tree" is loaded in memory that can be parsed in order to find out what devices are being emulated and what addresses they’re memory-mapped at. A few parameters are [passed through `a` registers](https://stackoverflow.com/a/72060395) when first running firmware code, with the address of this in register `a1`. Unfortunately this stuff is severely undocumented but the same convention exists [in coreboot](https://doc.coreboot.org/arch/riscv/index.html#stage-handoff-protocol) and [in OpenSBI](https://github.com/riscv-software-src/opensbi/blob/ce1d6188a2169c7771af1189cc8332e7a394cd19/platform/generic/platform.c#L59-L75).

With riscv-rt 0.8.1, by the time any Rust code runs all registers have been cleared so the DTF pointer cannot be found in `a1`. I have [a workaround](https://github.com/SimonSapin/riscv-qemu-demo/blob/5a1f80397e98bea572cf4bbf156f20fe0b96befb/src/main.rs#L24-L40) but it relies on QEMU internals that might change across versions.

Would it make sense for riscv-rt at the very beginning of `_abs_start` to copy these arguments registers (or perhaps just `a1`) into some symbol in RAM?

**Comment by almindor** [comment]
We could provide something like this. I would feature-gate it since there's no "free real estate" to store it to. The place where this would be stored would also have to somehow be defined for this to work.

**Comment by SimonSapin** [comment]
Instead of specific behavior with an opt-in flag, could there be an optional hook for running code provided by another crate before the registers are reset? Are there constraints for code running this early? (For example, would it have to be assembly rather than Rust?)

**Comment by SimonSapin** [comment]
Never mind that last sentence, for this use case I’d need assembly anyway to access specific registers.

**Comment by Disasm** [comment]
Maybe we can pass all the `a<n>` register values to `start_rust` and then to `main`? This should be relatively cheap and universal (also compatible with multi-core hardware).

**Comment by SimonSapin** [comment]
This is a very elegant solution, but doesn’t this require carrying these values somewhere all the way through initialization code?

**Comment by SimonSapin** [comment]
An attempt at the "early hook" approach:

```diff
diff --git asm.S asm.S
index 910d359..0e7d7f8 100644
--- asm.S
+++ asm.S
@@ -42,7 +42,8 @@ _start:
 .option pop
     .endif
 
-_abs_start:
+.global _default_abs_start
+_default_abs_start:
     .cfi_startproc
     .cfi_undefined ra
 
diff --git link.x link.x
index e3b5ff4..93f2b8d 100644
--- link.x
+++ link.x
@@ -4,6 +4,7 @@ PROVIDE(_max_hart_id = 0);
 PROVIDE(_hart_stack_size = 2K);
 PROVIDE(_heap_size = 0);
 
+PROVIDE(_abs_start = _default_abs_start);
 PROVIDE(UserSoft = DefaultHandler);
 PROVIDE(SupervisorSoft = DefaultHandler);
 PROVIDE(MachineSoft = DefaultHandler);
```

In the user crate:

```rust
extern "C" {
    pub static DEVICE_TREE_PTR: *const u8;
}

core::arch::global_asm!(
    r#"
    .section init, "ax"
    .global _abs_start
        la t0, DEVICE_TREE_PTR
        sw a1, 0(t0)
        j _default_abs_start

    .section data
    .global DEVICE_TREE_PTR
    DEVICE_TREE_PTR:
        .4byte 0
    "#
);
```

`DEVICE_TREE_PTR` is not a Rust static because that would be overwritten by `r0::init_data`.

But it looks like my symbol definitions in `global_asm!` don’t work:

* `println!("{:p}", &device_tree::DEVICE_TREE_PTR as *const *const u8)` prints `0x0`
* `_start` jumps to `_default_abs_start`, not my `_abs_start`:

```asm
(gdb) break _start
Breakpoint 1 at 0x80000000: file asm.S, line 27.
(gdb) c
Continuing.

Breakpoint 1, _start () at asm.S:27
27      asm.S: No such file or directory.
(gdb) x/5i $pc
=> 0x80000000 <_start>: lui     ra,0x80000
   0x80000004 <_start+4>:       jr      8(ra)
   0x80000008 <_default_abs_start>:     csrwi   mie,0
   0x8000000c <_default_abs_start+4>:   csrwi   mip,0
   0x80000010 <_default_abs_start+8>:   li      ra,0

**Comment by Disasm** [comment]
`.data` gets copied in `r0::init_data(&mut _sdata, &mut _edata, &_sidata);`, that's why you have 0 there.

> This is a very elegant solution, but doesn’t this require carrying these values somewhere all the way through initialization code?

Yes, this will require additional code to save/restore registers, but I don't think that it will be a lot of code, especially for just 3 registers.

**Comment by SimonSapin** [comment]
> An attempt at the "early hook" approach:

I’ve found the bug. Section names are `.init` and `.data`, not `init` and `data` :sweat_smile: 

While passing arguments to `main` would look nice, handling the different signatures seems like a headache. I’ve submitted https://github.com/rust-embedded/riscv-rt/pull/94
